site:
  title: Learn Playwright Antora Pilot
  start_page: demoqa-docs::index.adoc

content:
  sources:
    - url: ../..
      start_path: spikes/antora-pilot/demoqa-docs

runtime:
  fetch: false

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build/site
